### ISSUE TITLE
Incompatibility with portable-atomic

### ISSUE THREAD

**Issue by bugadani** [esp-rs/riscv-atomic-emulation-trap#11]
`-imc` targets that use this crate and add `target-feature=+a` (i.e. at least ESP32-C2, ESP32-C3) can't use portable-atomic. This is starting to become painful as `atomic-polyfill` is deprecated and the ecosystem has started moving away from it.

**Comment by MabezDev** [comment]
They are incompatible. We've opted to use only portable-atomic in esp-hal now.
