### ISSUE TITLE
IllegalInstruction exception when using `embassy` in release mode

### ISSUE THREAD

**Issue by TheButlah** [esp-rs/riscv-atomic-emulation-trap#3]
I opened an issue in embassy for this but I believe it actually belongs here.
[Here](https://github.com/embassy-rs/embassy/issues/995#issuecomment-1266569722) is a minimally reproducible example.

Now, my understanding of all of this is *very* limited so take what I say with a grain of salt, but it appears as though either the atomics are not actually properly emulated, or that there is some sort of low level safety issue happening.

I have been able to confirm that if I don't use embassy and just try using a combination of `core::sync::atomic` and `critical_section::Mutex` and do stuff, I wasn't able to reproduce the issue. So using embassy appears to be the best way to reproduce the bug.

The bug *only* occurs when compiling for the `-imac` instruction set, and only when embassy is built with `opt-level = 1` or higher. This code works as expected in `opt-level = 0`.

In case its helpful, [here](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$qEDyxakwWlihYHeT_Jm-GTqU595A4Xi6I6HlzXOOt1U?via=matrix.org&via=tchncs.de&via=privacytools.io) is some additional context from the esp-rs matrix server, where @dirbaio did some digging into alternative workarounds that might make the trap handler obsolete. Please note that regardless, there is still a bug in the atomic trap handler

**Comment by bjoernQ** [comment]
The issue is caused by multiple problems - also in esp-hal!

However I found the problem here:  https://github.com/esp-rs/riscv-atomic-emulation-trap/blob/4131904611aafd6e435e292fc057f6daa300c52b/src/lib.rs#L10

The slot for X0 is used for the PC in the trap-frame but that breaks emulation of instruction that use `x0` as an nice way to safe a register when dealing with zero (e.g. `amoswap.w.aqrl a0,zero,(a0)`)

**Comment by bjoernQ** [comment]
The issue for the problem in esp-hal is here: https://github.com/esp-rs/esp-hal/issues/206
I have a fix ready but need #4 merged and released before

**Comment by bjoernQ** [comment]
@TheButlah The two mentioned PRs should (together) fix the issue. You can try it locally by patching the dependencies. Your example worked for me this way but would be great if you could give it a try

**Comment by TheButlah** [comment]
Will try soon! Y'all are awesome, thank you so much for putting up with my barrage of matrix messages ❤

**Comment by TheButlah** [comment]
Btw I saw somewhere that this would cause problems with esp-wifi, is that true? I was going to try out esp-wifi next

**Comment by TheButlah** [comment]
I have tested by patching `esp32c3-hal` to the latest commit, and that pulls in the new version of the trap handler. I can confirm that it fixes the problem. Thanks!
